platform :ios, "8.0"
use_frameworks!

target 'MWPhotoBrowser_Example' do
    pod 'MWPhotoBrowser', :path => "../"
    pod 'DACircularProgress'
    pod 'MBProgressHUD'
    pod 'SDWebImage'
end

target 'MWPhotoBrowser_Tests' do
  pod 'MWPhotoBrowser', :path => "../"
  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
